name: Convert Markdown to HTML

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install markdown Pygments

    - name: Run markdown conversion script
      run: python convert_markdown.py

    - name: Commit HTML file
      run: |
        git config --global user.name "alie8096"
        git config --global user.email "ali.e.8096@outlook.com"
        git add -A
        git commit -am "Update HTML file"
        git push origin main
      env:
        GITHUB_TOKEN: ${{ secrets.MY_LINKS_TOKEN }}
